# Generated by Django 4.0.4 on 2022-06-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('classify', models.CharField(max_length=255)),
                ('img', models.FileField(null=True, upload_to='')),
                ('discription', models.CharField(max_length=255)),
                ('movie_runtime', models.IntegerField()),
                ('onlien_time', models.DateTimeField(auto_now=True)),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('seats', models.CharField(default='', max_length=255)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField()),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='movie.films')),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='movie.studio')),
            ],
        ),
    ]
