# Generated by Django 4.0.4 on 2022-06-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.films'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.studio'),
        ),
    ]
