# Generated by Django 4.0.4 on 2022-06-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_sessions_film_alter_sessions_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.FileField(default='user1.jpg', upload_to='photo'),
        ),
    ]
