# Generated by Django 4.0.4 on 2022-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='seats',
            field=models.CharField(default='', max_length=255),
        ),
    ]
