# Generated by Django 4.0.4 on 2022-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_sessions_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='garble', max_length=64),
        ),
    ]
