# Generated by Django 4.0.4 on 2022-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_order_user_id_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
